# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class HomebrewEnvManagerV2 < Formula
  desc "Environment variable manager for aws amplify, dgo apps and oci object storage,"
  homepage "https://github.com/stanyzra/homebrew-env-manager-v2"
  url "https://github.com/stanyzra/homebrew-env-manager-v2/archive/refs/tags/v2.1.1.tar.gz"
  sha256 "c6683c9c8b97462b9f904d8649323e9deaaedf946650ffa4b61500163ea761e8"
  license "Apache-2.0"

  depends_on "go" => :build

  def install
    system "go", "build", "-o", bin/"env-manager-v2"
  end

  test do
    assert_match "env-manager-v2 version 2.1.0", shell_output("#{bin}/env-manager-v2 --version")
  end
end
