# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class HomebrewEnvManagerV2 < Formula
  desc "Environment variable manager for aws amplify, dgo apps and oci object storage,"
  homepage "https://github.com/stanyzra/homebrew-env-manager-v2"
  url "https://github.com/stanyzra/homebrew-env-manager-v2/archive/refs/tags/v0.4.0.tar.gz"
  sha256 "065e6a10c4cddb5aa0791c5af2ac7626049ddfc958b9e70c89c30a3b0b7d5ef4"
  license "Apache-2.0"

  depends_on "go" => :build

  def install
    system "go", "build", "-o", bin/"env-manager-v2"
  end

  test do
    assert_match "0.4.0", shell_output("#{bin}/env-manager-v2 --version")
  end
end
